# -*- coding: utf-8 -*-
"""OOP_Pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HvlTE2j99kusVKxrcqxCC0GK-NRRPPYC
"""

# imports
import cv2
import math
import numpy as np
import matplotlib.pyplot as plt
from collections import defaultdict
import os
from scipy.interpolate import griddata
from tkinter.filedialog import askopenfilename, askopenfilenames
from dataclasses import dataclass, field

'''
# data model
ObjectImageSet
ImageCollection

# low-level utilities
extract_prefix_and_view
normalize_filename
load_and_resize

# scientific functions
reconstruct_sphere_from_six_images
project_stereographic
project_lambert
project_sinusoidal
render_projection_image

# orchestration
ProjectionPipeline
'''

EXPECTED_VIEWS = {"front", "back", "left", "right", "top", "bottom"}

# low-level utilities

def normalize_filename(filename):
    return filename.lower().replace("-", "_").strip()


def extract_prefix_and_view(filepath):
    fname = os.path.basename(filepath)
    stem, _ = os.path.splitext(fname)
    stem = normalize_filename(stem)

    parts = stem.split("_")
    if len(parts) < 2:
        raise ValueError(f"Could not parse prefix/view from filename: {fname}")

    view = parts[-1]
    prefix = "_".join(parts[:-1])

    if view not in EXPECTED_VIEWS:
        raise ValueError(f"Unrecognized view '{view}' in filename: {fname}")

    return prefix, view


def load_and_resize(filepath, size=None):
    img = cv2.imread(filepath)
    if img is None:
        raise FileNotFoundError(f"Could not load image: {filepath}")

    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    if size is not None:
        img = cv2.resize(img, (size, size))

    return img

# data model

class ObjectImageSet:
    def __init__(self, path, prefix, files_by_view=None):
        self.path = path
        self.prefix = prefix
        self.files_by_view = {} if files_by_view is None else files_by_view

    def add_file(self, filepath):
        prefix, view = extract_prefix_and_view(filepath)

        if prefix != self.prefix:
            raise ValueError(f"File {filepath} does not match prefix {self.prefix}")

        self.files_by_view[view] = filepath

    def has_all_six_views(self):
        return EXPECTED_VIEWS.issubset(set(self.files_by_view.keys()))

    def missing_views(self):
        return EXPECTED_VIEWS - set(self.files_by_view.keys())

    def validate(self):
        if not self.has_all_six_views():
            raise ValueError(
                f"Object '{self.prefix}' is missing views: {sorted(self.missing_views())}"
            )

    def load_images(self, size=None):
        images = {}

        for view, filepath in self.files_by_view.items():
            images[view] = load_and_resize(filepath, size=size)

        return images

    def load_images_in_order(self, size=None):
        self.validate()
        images = self.load_images(size=size)

        return (
            images["front"],
            images["back"],
            images["left"],
            images["right"],
            images["top"],
            images["bottom"],
        )

class ImageCollection:
    def __init__(self, path=""):
        self.path = path
        self.objects = {}

    def add_file(self, filepath):
        prefix, view = extract_prefix_and_view(filepath)

        if prefix not in self.objects:
            self.objects[prefix] = ObjectImageSet(self.path, prefix)

        self.objects[prefix].add_file(filepath)

    def add_files(self, filepaths):
        for filepath in filepaths:
            self.add_file(filepath)

    def get_prefixes(self):
        return list(self.objects.keys())

    def get_object(self, prefix):
        return self.objects[prefix]

    def validate_all(self):
        for obj in self.objects.values():
            obj.validate()

# Scientific Functions

def getInverseOrthographicProjection(img, step=2):
    """
    Convert one orthographic face image (already loaded as an RGB array)
    into sampled points on the upper hemisphere in local face coordinates.

    Parameters
    ----------
    img : np.ndarray
        RGB image array of shape (H, W, 3).
    step : int
        Pixel stride for downsampling during sampling.

    Returns
    -------
    U, V, W : np.ndarray
        Local sphere coordinates on the face.
    COLORS : np.ndarray
        RGB colors scaled to [0, 1].
    WEIGHTS : np.ndarray
        Blending weights, larger near the image center.
    """
    height_img, width_img, _ = img.shape

    U, V, W = [], [], []
    COLORS = []
    WEIGHTS = []

    for i in range(0, width_img, step):
        for j in range(0, height_img, step):

            # Map pixel coordinates to [-1, 1] x [-1, 1]
            x_img = (2 * i / (width_img - 1)) - 1
            y_img = (2 * j / (height_img - 1)) - 1

            # Flip y-axis so positive is upward
            y_img = -y_img

            # Restrict to unit disk
            if x_img**2 + y_img**2 > 1:
                continue

            # Inverse orthographic projection onto unit sphere
            u = x_img
            v = y_img
            w = math.sqrt(max(0, 1 - (u**2 + v**2)))

            U.append(u)
            V.append(v)
            W.append(w)

            COLORS.append(img[j, i] / 255.0)
            WEIGHTS.append(w**2)

    return (
        np.array(U),
        np.array(V),
        np.array(W),
        np.array(COLORS),
        np.array(WEIGHTS)
    )


def getGlobalSphereCoords(U, V, W, view):
    """
    Convert local face coordinates (U, V, W) into global sphere coordinates
    based on which cube/face view the image represents.
    """
    if view == "front":
        return U, -W, V
    elif view == "back":
        return -U, W, V
    elif view == "left":
        return -W, -U, V
    elif view == "right":
        return W, U, V
    elif view == "top":
        return U, V, W
    elif view == "bottom":
        return -U, V, -W
    else:
        raise ValueError(f"Unknown view: {view}")


def process_one_face(img, view, step=2):
    """
    Process one face image:
    image -> local sphere coords -> global sphere coords
    """
    U, V, W, colors_face, weights_face = getInverseOrthographicProjection(img, step=step)
    X, Y, Z = getGlobalSphereCoords(U, V, W, view)
    return X, Y, Z, colors_face, weights_face


def constructFullSphereFromSixImages(top, bottom, front, back, left, right, step=2):
    """
    Reconstruct a full sphere by combining six orthographic images.

    Parameters
    ----------
    top, bottom, front, back, left, right : np.ndarray
        RGB image arrays for the six faces.
    step : int
        Pixel stride used during inverse orthographic sampling.

    Returns
    -------
    X, Y, Z : np.ndarray
        Global sphere coordinates.
    COLORS : np.ndarray
        RGB colors.
    WEIGHTS : np.ndarray
        Weights for later blending.
    """
    view_images = {
        "front": front,
        "back": back,
        "left": left,
        "right": right,
        "top": top,
        "bottom": bottom,
    }

    views = ["front", "back", "left", "right", "top", "bottom"]

    X_list, Y_list, Z_list = [], [], []
    COLORS_list, WEIGHTS_list = [], []

    for view in views:
        img = view_images[view]
        X, Y, Z, colors_face, weights_face = process_one_face(img, view, step=step)

        X_list.append(X)
        Y_list.append(Y)
        Z_list.append(Z)
        COLORS_list.append(colors_face)
        WEIGHTS_list.append(weights_face)

    X = np.concatenate(X_list)
    Y = np.concatenate(Y_list)
    Z = np.concatenate(Z_list)
    COLORS = np.concatenate(COLORS_list)
    WEIGHTS = np.concatenate(WEIGHTS_list)

    return X, Y, Z, COLORS, WEIGHTS


def blendSphereColors(X, Y, Z, COLORS, WEIGHTS, decimals=3):
    """
    Blend overlapping sphere points using weighted averaging after binning
    nearby points by rounded coordinates.
    """
    bins = {}

    for x, y, z, color, weight in zip(X, Y, Z, COLORS, WEIGHTS):
        key = (round(x, decimals), round(y, decimals), round(z, decimals))

        if key not in bins:
            bins[key] = {
                "xyz_sum": np.array([0.0, 0.0, 0.0]),
                "color_sum": np.array([0.0, 0.0, 0.0]),
                "weight_sum": 0.0
            }

        bins[key]["xyz_sum"] += weight * np.array([x, y, z])
        bins[key]["color_sum"] += weight * color
        bins[key]["weight_sum"] += weight

    X_blend, Y_blend, Z_blend, COLORS_blend = [], [], [], []

    for entry in bins.values():
        wsum = entry["weight_sum"]
        xyz_avg = entry["xyz_sum"] / wsum
        color_avg = entry["color_sum"] / wsum

        X_blend.append(xyz_avg[0])
        Y_blend.append(xyz_avg[1])
        Z_blend.append(xyz_avg[2])
        COLORS_blend.append(color_avg)

    return (
        np.array(X_blend),
        np.array(Y_blend),
        np.array(Z_blend),
        np.array(COLORS_blend)
    )


def stereographicallyProjectFromSphere(X, Y, Z, COLORS, z_max=0.9):
    """
    Stereographic projection from the north pole onto the plane.
    Points too close to the north pole are skipped.
    """
    X_stereo, Y_stereo, COLORS_stereo = [], [], []

    for x, y, z, color in zip(X, Y, Z, COLORS):
        if z > z_max:
            continue

        x_s = -2 * x / (z - 1)
        y_s = -2 * y / (z - 1)

        X_stereo.append(x_s)
        Y_stereo.append(y_s)
        COLORS_stereo.append(color)

    return np.array(X_stereo), np.array(Y_stereo), np.array(COLORS_stereo)


def stereographicallyProjectFromSphereSouth(X, Y, Z, COLORS, z_min=-0.9):
    """
    Stereographic projection from the south pole onto the plane.
    Points too close to the south pole are skipped.
    """
    X_stereo2, Y_stereo2, COLORS_stereo2 = [], [], []

    for x, y, z, color in zip(X, Y, Z, COLORS):
        if z < z_min:
            continue

        x_s = 2 * x / (z + 1)
        y_s = 2 * y / (z + 1)

        X_stereo2.append(x_s)
        Y_stereo2.append(y_s)
        COLORS_stereo2.append(color)

    return np.array(X_stereo2), np.array(Y_stereo2), np.array(COLORS_stereo2)


def projectCylindricalLambert(X, Y, Z, COLORS):
    """
    Lambert cylindrical-style parameterization:
    longitude lambda and height z.
    """
    X_lambert, Y_lambert, COLORS_lambert = [], [], []

    for x, y, z, color in zip(X, Y, Z, COLORS):
        lam = math.atan2(y, x)
        t = z

        X_lambert.append(lam)
        Y_lambert.append(t)
        COLORS_lambert.append(color)

    return np.array(X_lambert), np.array(Y_lambert), np.array(COLORS_lambert)

# visualization and plotting functions

def plot_points_3d_views(X, Y, Z, COLORS,
                         title="3D sphere",
                         prefix="object",
                         suffix="raw",
                         save=True,
                         folder="outputs",
                         max_points=500000,
                         dpi=200,
                         point_size=1,
                         views=None):
    """
    Plot a colored 3D point cloud of a sphere from several viewing angles.
    """

    if not (len(X) == len(Y) == len(Z) == len(COLORS)):
        raise ValueError("X, Y, Z, and COLORS must all have the same length.")

    n = len(X)
    print("Total points:", n)

    # randomly sample if too large
    if n > max_points:
        idx = np.random.choice(n, size=max_points, replace=False)
        X = X[idx]
        Y = Y[idx]
        Z = Z[idx]
        COLORS = COLORS[idx]
        print(f"Downsampled to {max_points} points")

    # default views
    if views is None:
        views = [
            (20,   30,  "front_right"),
            (20,  120,  "front_left"),
            (20, -60,   "back_right"),
            (20, -150,  "back_left"),
            (90,   0,   "top"),
            (-90,  0,   "bottom"),
        ]

    if save:
        folder = f"{folder}_{prefix}"
        os.makedirs(folder, exist_ok=True)

    for elev, azim, view_label in views:
        fig = plt.figure(figsize=(8, 8))
        ax = fig.add_subplot(111, projection='3d')

        ax.scatter(X, Y, Z, c=COLORS, s=point_size, depthshade=False)

        ax.set_box_aspect([1, 1, 1])
        ax.set_xlabel("X")
        ax.set_ylabel("Y")
        ax.set_zlabel("Z")

        full_title = f"{prefix} - {title} ({view_label})"
        ax.set_title(full_title)
        ax.view_init(elev=elev, azim=azim)

        if save:
            filename = f"{prefix}_{suffix}_3D_{view_label}.png"
            filepath = os.path.join(folder, filename)
            fig.savefig(filepath, dpi=dpi, bbox_inches='tight')
            print(f"Saved: {filepath}")

        plt.show()
        plt.close()


def plot_stereographic(Xs, Ys, COLORS,
                       title="Stereographic Projection",
                       prefix="object",
                       suffix="stereo",
                       save=True,
                       folder="outputs"):

    if not (len(Xs) == len(Ys) == len(COLORS)):
        raise ValueError("Xs, Ys, and COLORS must all have the same length.")

    fig = plt.figure(figsize=(8, 8))
    plt.scatter(Xs, Ys, c=COLORS, s=1)

    plt.gca().set_aspect('equal')
    plt.title(f"{prefix} - {title}")
    plt.xlabel("x")
    plt.ylabel("y")

    if save:
        folder = f"{folder}_{prefix}"
        os.makedirs(folder, exist_ok=True)

        filename = f"{prefix}_{suffix}_stereographic.png"
        filepath = os.path.join(folder, filename)

        fig.savefig(filepath, dpi=200, bbox_inches='tight')
        print(f"Saved: {filepath}")

    plt.show()
    plt.close()


def plot_lambert(Xs, Ys, COLORS,
                 title="Lambert Cylindrical Projection",
                 prefix="object",
                 suffix="lambert",
                 save=True,
                 folder="outputs"):

    if not (len(Xs) == len(Ys) == len(COLORS)):
        raise ValueError("Xs, Ys, and COLORS must all have the same length.")

    fig = plt.figure(figsize=(10, 5))
    plt.scatter(Xs, Ys, c=COLORS, s=1)

    plt.gca().set_aspect('auto')
    plt.title(f"{prefix} - {title}")
    plt.xlabel("Longitude (λ)")
    plt.ylabel("Height (z)")

    plt.xlim(-np.pi, np.pi)
    plt.ylim(-1, 1)

    if save:
        folder = f"{folder}_{prefix}"
        os.makedirs(folder, exist_ok=True)

        filename = f"{prefix}_{suffix}_lambert.png"
        filepath = os.path.join(folder, filename)

        fig.savefig(filepath, dpi=200, bbox_inches='tight')
        print(f"Saved: {filepath}")

    plt.show()
    plt.close()

def render_stereographic_image(Xs, Ys, COLORS,
                               grid_res=800,
                               method='linear',
                               r_max=None,   # 👈 NEW
                               title="Stereographic Projection",
                               prefix="object",
                               suffix="interpolated",
                               save=True,
                               folder="outputs"):

    # -------------------------
    # OPTIONAL RADIAL CROP
    # -------------------------
    if r_max is not None:
        R = np.sqrt(Xs**2 + Ys**2)
        mask = R <= r_max

        Xs = Xs[mask]
        Ys = Ys[mask]
        COLORS = COLORS[mask]

    # bounding box of (possibly cropped) points
    x_min, x_max = Xs.min(), Xs.max()
    y_min, y_max = Ys.min(), Ys.max()

    # -------------------------
    # GRID
    # -------------------------
    xi = np.linspace(x_min, x_max, grid_res)
    yi = np.linspace(y_min, y_max, grid_res)
    XI, YI = np.meshgrid(xi, yi)

    # -------------------------
    # INTERPOLATION
    # -------------------------
    Rch = griddata((Xs, Ys), COLORS[:, 0], (XI, YI), method=method)
    Gch = griddata((Xs, Ys), COLORS[:, 1], (XI, YI), method=method)
    Bch = griddata((Xs, Ys), COLORS[:, 2], (XI, YI), method=method)

    img = np.dstack([Rch, Gch, Bch])

    # fill holes with nearest
    Rn = griddata((Xs, Ys), COLORS[:, 0], (XI, YI), method='nearest')
    Gn = griddata((Xs, Ys), COLORS[:, 1], (XI, YI), method='nearest')
    Bn = griddata((Xs, Ys), COLORS[:, 2], (XI, YI), method='nearest')

    img_near = np.dstack([Rn, Gn, Bn])

    nan_mask = np.isnan(img)
    img[nan_mask] = img_near[nan_mask]

    img = np.clip(img, 0, 1)

    # -------------------------
    # PLOT
    # -------------------------
    plt.figure(figsize=(8, 8))
    plt.imshow(img, origin='lower', extent=[x_min, x_max, y_min, y_max])
    plt.gca().set_aspect('equal')
    plt.title(f"{prefix} - {title}")
    plt.xlabel("x")
    plt.ylabel("y")

    if save:
        folder = f"{folder}_{prefix}"
        os.makedirs(folder, exist_ok=True)

        filename = f"{prefix}_{suffix}.png"
        filepath = os.path.join(folder, filename)

        plt.imsave(filepath, img)
        print(f"Saved: {filepath}")

    plt.show()

    return img

def render_lambert_image(Xs, Ys, COLORS,
                         grid_res_x=1200,
                         grid_res_y=600,
                         method='linear',
                         seam_pad=0.15,
                         title="Lambert Cylindrical Projection",
                         prefix="object",
                         suffix="lambert_interp",
                         save=True,
                         folder="outputs"):

    # original arrays
    Xs = np.asarray(Xs)
    Ys = np.asarray(Ys)
    COLORS = np.asarray(COLORS)

    # duplicate points near seam so interpolation wraps better
    X_aug = [Xs]
    Y_aug = [Ys]
    C_aug = [COLORS]

    left_mask = Xs < (-np.pi + seam_pad)
    right_mask = Xs > (np.pi - seam_pad)

    if np.any(left_mask):
        X_aug.append(Xs[left_mask] + 2*np.pi)
        Y_aug.append(Ys[left_mask])
        C_aug.append(COLORS[left_mask])

    if np.any(right_mask):
        X_aug.append(Xs[right_mask] - 2*np.pi)
        Y_aug.append(Ys[right_mask])
        C_aug.append(COLORS[right_mask])

    X_all = np.concatenate(X_aug)
    Y_all = np.concatenate(Y_aug)
    C_all = np.concatenate(C_aug)

    # fixed Lambert domain
    xi = np.linspace(-np.pi, np.pi, grid_res_x)
    yi = np.linspace(-1, 1, grid_res_y)
    XI, YI = np.meshgrid(xi, yi)

    # interpolate RGB channels
    R = griddata((X_all, Y_all), C_all[:, 0], (XI, YI), method=method)
    G = griddata((X_all, Y_all), C_all[:, 1], (XI, YI), method=method)
    B = griddata((X_all, Y_all), C_all[:, 2], (XI, YI), method=method)

    img = np.dstack([R, G, B])

    # fill holes with nearest neighbor
    Rn = griddata((X_all, Y_all), C_all[:, 0], (XI, YI), method='nearest')
    Gn = griddata((X_all, Y_all), C_all[:, 1], (XI, YI), method='nearest')
    Bn = griddata((X_all, Y_all), C_all[:, 2], (XI, YI), method='nearest')
    img_near = np.dstack([Rn, Gn, Bn])

    mask = np.isnan(img)
    img[mask] = img_near[mask]

    img = np.clip(img, 0, 1)

    plt.figure(figsize=(12, 6))
    plt.imshow(img, origin='lower', extent=[-np.pi, np.pi, -1, 1], aspect='auto')
    plt.title(f"{prefix} - {title}")
    plt.xlabel("Longitude (λ)")
    plt.ylabel("Height (z)")

    if save:
        folder = f"{folder}_{prefix}"
        os.makedirs(folder, exist_ok=True)

        # save raw image (correct orientation)
        filepath_img = os.path.join(folder, f"{prefix}_{suffix}_raw.png")
        plt.imsave(filepath_img, np.flipud(img), vmin=0, vmax=1)
        print(f"Saved raw image: {filepath_img}")

        # save plotted version (with axes, labels, etc.)
        filepath_plot = os.path.join(folder, f"{prefix}_{suffix}_plot.png")
        plt.savefig(filepath_plot, dpi=200, bbox_inches='tight')
        print(f"Saved plot: {filepath_plot}")

    plt.show()
    plt.close()

    return img

from tqdm.notebook import tqdm

class ProjectionPipeline:
    def __init__(self, image_collection):
        """
        Store the ImageCollection so the pipeline can access all grouped objects.
        """
        self.image_collection = image_collection

    def process_one_object(self, prefix, size=None, step=2, blend=True):
        """
        Process one object from its six input images into a reconstructed sphere.

        Parameters
        ----------
        prefix : str
            Object name/prefix, e.g. "testball".
        size : int or None
            If not None, resize each input face image to (size, size) before processing.
        step : int
            Pixel stride used during inverse orthographic sampling.
            Larger step means fewer sampled pixels and faster runtime.
        blend : bool
            Whether to blend overlapping points from different faces.

        Returns
        -------
        result : dict
            Dictionary containing reconstructed coordinates, colors, and metadata.
        """
        obj = self.image_collection.get_object(prefix)

        # Load the six face images in a fixed order
        front, back, left, right, top, bottom = obj.load_images_in_order(size=size)

        # Reconstruct the full sphere from the six faces
        X, Y, Z, COLORS, WEIGHTS = constructFullSphereFromSixImages(
            top, bottom, front, back, left, right, step=step
        )

        # Blend overlapping regions if requested
        # decimals=2 matches the smoother behavior from your older pipeline
        if blend:
            X, Y, Z, COLORS = blendSphereColors(X, Y, Z, COLORS, WEIGHTS, decimals=2)
            WEIGHTS = None

        return {
            "prefix": prefix,
            "X": X,
            "Y": Y,
            "Z": Z,
            "COLORS": COLORS,
            "WEIGHTS": WEIGHTS,
            "step": step,
            "size": size,
            "blend": blend
        }

    def process_all_objects(self, size=None, step=2, blend=True, show_progress=True):
        """
        Process all objects in the ImageCollection.

        Parameters
        ----------
        size : int or None
            Optional resize dimension for each face image.
        step : int
            Pixel stride used during inverse orthographic sampling.
        blend : bool
            Whether to blend overlapping face contributions.
        show_progress : bool
            Whether to show a tqdm progress bar.

        Returns
        -------
        results : dict
            Dictionary mapping each prefix to its processed result dictionary.
        """
        results = {}
        prefixes = self.image_collection.get_prefixes()

        iterable = tqdm(prefixes, desc="Processing objects") if show_progress else prefixes

        for prefix in iterable:
            try:
                if show_progress:
                    iterable.set_postfix_str(prefix)

                results[prefix] = self.process_one_object(
                    prefix, size=size, step=step, blend=blend
                )
            except Exception as e:
                print(f"Skipping {prefix}: {e}")

        return results

    def plot_3d_result(self, result, save=True, folder="outputs", max_points=1000000):
        """
        Plot the reconstructed sphere as a 3D colored point cloud.
        """
        suffix = f"raw_step{result['step']}"

        plot_points_3d_views(
            result["X"],
            result["Y"],
            result["Z"],
            result["COLORS"],
            prefix=result["prefix"],
            suffix=suffix,
            save=save,
            folder=folder,
            max_points=max_points
        )

    # -------------------------
    # NORTH-POLE STEREOGRAPHIC
    # -------------------------

    def plot_stereographic_north_result(self, result, save=True, folder="outputs", z_max=0.75):
        """
        Plot the north-pole stereographic projection.

        Projecting FROM the north pole places the south pole near the center.
        """
        Xs, Ys, COLORSs = stereographicallyProjectFromSphere(
            result["X"], result["Y"], result["Z"], result["COLORS"], z_max=z_max
        )

        suffix = f"stereo_north_step{result['step']}_zmax{z_max}"

        plot_stereographic(
            Xs, Ys, COLORSs,
            title="North Pole Stereographic Projection",
            prefix=result["prefix"],
            suffix=suffix,
            save=save,
            folder=folder
        )

    def render_stereographic_north_image_result(self, result,
                                                r_max=None,
                                                grid_res=800,
                                                method='linear',
                                                z_max=0.75,
                                                save=True,
                                                folder="outputs"):
        """
        Render an interpolated image from the north-pole stereographic projection.

        If r_max is None, choose it automatically from the 95th percentile
        of projected radii to crop away extreme distorted outer regions.
        """
        Xs, Ys, COLORSs = stereographicallyProjectFromSphere(
            result["X"], result["Y"], result["Z"], result["COLORS"], z_max=z_max
        )

        if r_max is None:
            r_max = np.percentile(np.sqrt(Xs**2 + Ys**2), 90)

        suffix = f"stereo_north_interp_step{result['step']}_zmax{z_max}_r{round(r_max, 2)}"

        img = render_stereographic_image(
            Xs, Ys, COLORSs,
            grid_res=grid_res,
            method=method,
            r_max=r_max,
            title="North Pole Stereographic Projection",
            prefix=result["prefix"],
            suffix=suffix,
            save=save,
            folder=folder
        )

        return img

    # -------------------------
    # SOUTH-POLE STEREOGRAPHIC
    # -------------------------

    def plot_stereographic_south_result(self, result, save=True, folder="outputs", z_min=-0.75):
        """
        Plot the south-pole stereographic projection.

        Projecting FROM the south pole places the north pole near the center.
        """
        Xs, Ys, COLORSs = stereographicallyProjectFromSphereSouth(
            result["X"], result["Y"], result["Z"], result["COLORS"], z_min=z_min
        )

        suffix = f"stereo_south_step{result['step']}_zmin{z_min}"

        plot_stereographic(
            Xs, Ys, COLORSs,
            title="South Pole Stereographic Projection",
            prefix=result["prefix"],
            suffix=suffix,
            save=save,
            folder=folder
        )

    def render_stereographic_south_image_result(self, result,
                                                r_max=None,
                                                grid_res=800,
                                                method='linear',
                                                z_min=-0.75,
                                                save=True,
                                                folder="outputs"):
        """
        Render an interpolated image from the south-pole stereographic projection.

        If r_max is None, choose it automatically from the 95th percentile
        of projected radii to crop away extreme distorted outer regions.
        """
        Xs, Ys, COLORSs = stereographicallyProjectFromSphereSouth(
            result["X"], result["Y"], result["Z"], result["COLORS"], z_min=z_min
        )

        if r_max is None:
            r_max = np.percentile(np.sqrt(Xs**2 + Ys**2), 90)

        suffix = f"stereo_south_interp_step{result['step']}_zmin{z_min}_r{round(r_max, 2)}"

        img = render_stereographic_image(
            Xs, Ys, COLORSs,
            grid_res=grid_res,
            method=method,
            r_max=r_max,
            title="South Pole Stereographic Projection",
            prefix=result["prefix"],
            suffix=suffix,
            save=save,
            folder=folder
        )

        return img

    # -------------------------
    # LAMBERT
    # -------------------------

    def plot_lambert_result(self, result, save=True, folder="outputs"):
        """
        Plot the Lambert cylindrical projection as a scatter plot.
        """
        Xl, Yl, COLORSl = projectCylindricalLambert(
            result["X"], result["Y"], result["Z"], result["COLORS"]
        )

        suffix = f"lambert_step{result['step']}"

        plot_lambert(
            Xl, Yl, COLORSl,
            prefix=result["prefix"],
            suffix=suffix,
            save=save,
            folder=folder
        )

    def render_lambert_image_result(self, result,
                                    grid_res_x=1200,
                                    grid_res_y=600,
                                    method='linear',
                                    save=True,
                                    folder="outputs"):
        """
        Render an interpolated Lambert cylindrical image.
        """
        Xl, Yl, COLORSl = projectCylindricalLambert(
            result["X"], result["Y"], result["Z"], result["COLORS"]
        )

        suffix = f"lambert_interp_step{result['step']}"

        img = render_lambert_image(
            Xl, Yl, COLORSl,
            grid_res_x=grid_res_x,
            grid_res_y=grid_res_y,
            method=method,
            prefix=result["prefix"],
            suffix=suffix,
            save=save,
            folder=folder
        )

        return img

    # -------------------------
    # DOWNLOAD / EXPORT
    # -------------------------

    def download_result_folder(self, result):
        """
        Zip and download the output folder for one processed result.
        """
        import shutil
        from google.colab import files
        import os

        prefix = result["prefix"]
        folder_name = f"outputs_{prefix}"

        if not os.path.exists(folder_name):
            raise FileNotFoundError(f"Folder does not exist: {folder_name}")

        zip_path = shutil.make_archive(folder_name, 'zip', folder_name)
        files.download(zip_path)

    def download_all_result_folders(self):
        """
        Zip and download each output folder separately.
        """
        import shutil
        from google.colab import files
        import os

        for prefix in self.image_collection.get_prefixes():
            folder_name = f"outputs_{prefix}"

            if os.path.exists(folder_name):
                zip_path = shutil.make_archive(folder_name, 'zip', folder_name)
                print(f"Downloading {zip_path}")
                files.download(zip_path)
            else:
                print(f"Skipping {folder_name}: folder does not exist")

    def download_all_outputs_as_one_zip(self, zip_name="all_outputs"):
        """
        Gather all output folders into one temporary directory, zip them together,
        and download the single combined zip file.
        """
        import shutil
        import os
        from google.colab import files

        temp_root = "all_outputs_temp"
        os.makedirs(temp_root, exist_ok=True)

        copied_any = False

        for prefix in self.image_collection.get_prefixes():
            folder_name = f"outputs_{prefix}"
            if os.path.exists(folder_name):
                dest = os.path.join(temp_root, folder_name)
                if os.path.exists(dest):
                    shutil.rmtree(dest)
                shutil.copytree(folder_name, dest)
                copied_any = True
            else:
                print(f"Skipping {folder_name}: folder does not exist")

        if not copied_any:
            raise FileNotFoundError("No output folders found to archive.")

        zip_path = shutil.make_archive(zip_name, 'zip', temp_root)
        files.download(zip_path)

from google.colab import files
import os

all_filepaths = []

while True:
    user_input = input("Upload files? Press Enter to upload or type 'done' to finish: ")

    if user_input.lower() == "done":
        break

    uploaded = files.upload()

    for fname in uploaded.keys():
        filepath = os.path.join("/content", fname)
        all_filepaths.append(filepath)

    print("Current files:", all_filepaths)

print("\nFINAL FILE LIST:")
print(all_filepaths)

for fp in all_filepaths:
    print("FILE:", fp)
    print("PARSED:", extract_prefix_and_view(fp))

collection = ImageCollection(path="/content")
collection.add_files(all_filepaths)

print("\nPREFIXES:", collection.get_prefixes())

for prefix in collection.get_prefixes():
    obj = collection.get_object(prefix)
    print(f"\nOBJECT: {prefix}")
    print("files_by_view =", obj.files_by_view)
    print("has_all_six_views =", obj.has_all_six_views())
    print("missing_views =", obj.missing_views())

collection.validate_all()

pipeline = ProjectionPipeline(collection)

results = pipeline.process_all_objects(size=1024, step=1, blend=True, show_progress=True)

for prefix, result in results.items():
    pipeline.plot_3d_result(result, save=True)

    pipeline.plot_stereographic_north_result(result, save=True, z_max=0.75)
    pipeline.render_stereographic_north_image_result(result, save=True, z_max=0.75)

    pipeline.plot_stereographic_south_result(result, save=True, z_min=-0.75)
    pipeline.render_stereographic_south_image_result(result, save=True, z_min=-0.75)

    pipeline.plot_lambert_result(result, save=True)
    pipeline.render_lambert_image_result(result, save=True)

pipeline.download_all_outputs_as_one_zip()

